### ISSUE TITLE
Logo For Geolocator

### ISSUE THREAD

**Issue by zularizal** [brminnick/GeolocatorSample#2]
Hi @brminnick , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by brminnick** [comment]
Thanks @zularizal - that'd be great! 

Feel free to fork the repo and submit a Pull Request!

**Comment by zularizal** [comment]
Hi @brminnick , this design logo for your project. This logo is inspired by the pin map icon and coordinate icon.

I have made several color choices. Which one do you like?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/56087896-c38aad80-5e9e-11e9-9de9-d14fa3b20e00.png)

**Comment by brminnick** [comment]
I love it! Let's go with #2.

Are you familiar with the different image sizes for icons required by iOS & Android?

**Comment by zularizal** [comment]
Hi @brminnick , I have sent a pull request #3 

And also I have uploaded the logo and icon for Android and iOS to the drive.
https://drive.google.com/open?id=1gO4_-K8-ii9XUoKOf_MGHcD4RrBYLa8s

**Comment by brminnick** [comment]
Hey @zularizal! Would you be interested in making another app icon?

I'll be pushing this app to the app stores soon, and I'd love it if we could team up again to create the artwork!

https://github.com/brminnick/GitTrends/issues/5
